/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionparking;


import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.border.Border;
import com.itextpdf.layout.element.Paragraph;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import static javax.swing.JOptionPane.*;
//import sun.text.normalizer.RangeValueIterator.Element;


/*
 *
 * @author rrive
 */
public class PanelIngresarVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarVehiculo
     */
    public PanelIngresarVehiculo() throws ClassNotFoundException {
        initComponents();
       // this.setLocationRelativeTo(null);
      this.tfMatricula.requestFocus();
        button1.setEnabled(false);


        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex)
        {
            Logger.getLogger(PanelIngresarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                tfMatricula = new javax.swing.JTextField();
                tfPropietario = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                rbMoto = new javax.swing.JRadioButton();
                rbAuto = new javax.swing.JRadioButton();
                button1 = new java.awt.Button();
                jLabel1 = new javax.swing.JLabel();

                setMaximumSize(new java.awt.Dimension(1200, 650));
                setMinimumSize(new java.awt.Dimension(0, 0));
                setPreferredSize(new java.awt.Dimension(1200, 650));
                addAncestorListener(new javax.swing.event.AncestorListener() {
                        public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                        }
                        public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                        }
                        public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                                formAncestorRemoved(evt);
                        }
                });
                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                tfMatricula.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
                tfMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
                tfMatricula.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tfMatriculaActionPerformed(evt);
                        }
                });
                tfMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfMatriculaKeyReleased(evt);
                        }
                });
                add(tfMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 150, 30));

                tfPropietario.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
                tfPropietario.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tfPropietarioActionPerformed(evt);
                        }
                });
                tfPropietario.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfPropietarioKeyReleased(evt);
                        }
                });
                add(tfPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 320, 27));

                jLabel2.setText("Matrícula");
                add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

                jLabel3.setText("Nombre propietario");
                add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

                jLabel4.setText("Tipo de vehiculo");
                add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

                buttonGroup1.add(rbMoto);
                rbMoto.setText("Motocicleta");
                rbMoto.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                rbMotoKeyReleased(evt);
                        }
                });
                add(rbMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, -1, -1));

                buttonGroup1.add(rbAuto);
                rbAuto.setText("Coche");
                rbAuto.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbAutoActionPerformed(evt);
                        }
                });
                rbAuto.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                rbAutoKeyReleased(evt);
                        }
                });
                add(rbAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, -1, -1));

                button1.setBackground(new java.awt.Color(51, 255, 255));
                button1.setForeground(new java.awt.Color(255, 255, 255));
                button1.setLabel("Registrar");
                button1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                button1ActionPerformed(evt);
                        }
                });
                add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 99, 27));

                jLabel1.setBackground(new java.awt.Color(255, 255, 255));
                jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 51, 255));
                jLabel1.setText("Ingreso de vehículos a GestiónParking");
                jLabel1.setMaximumSize(new java.awt.Dimension(0, 0));
                jLabel1.setMinimumSize(new java.awt.Dimension(600, 300));
                add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 250, 42));
        }// </editor-fold>//GEN-END:initComponents

    String fechaHora = "";
     public static final String DEST = "gestionparkingbd/hello_world.pdf";

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

 		String matricula= "";
		String propietario="";
    	String moto="";
	    String auto="";

        String clasevehiculo = "";

    if (!tfMatricula.getText().trim().equals("") && !tfPropietario.getText().trim().equals("") && !rbAuto.getText().trim().equals("") && !rbMoto.getText().trim().equals("")){

     } else {
         JOptionPane.showMessageDialog(null, "Llene todos los campos");
       }

        if (rbAuto.isSelected()) {
            clasevehiculo = "Automovil";
        }
        if (rbMoto.isSelected()) {
            clasevehiculo = "Motocicleta";
        }
        try {
            Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/gestionparkingbd", "root", "");
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Calendar cal = Calendar.getInstance();
            Date date = cal.getTime();
            fechaHora = dateFormat.format(date);
            System.out.print(dateFormat.format(date));
            Statement stat = conexion.createStatement();
            String sql = "INSERT INTO vehiculos (matricula, propietario,tipovehiculo,horaentrada,estado) VALUES ('" + tfMatricula.getText() + "','" + tfPropietario.getText() + "','" + clasevehiculo + "','" + fechaHora + "','Disponible')";
            stat.executeUpdate(sql);

            showMessageDialog(null, "El vehículo se registró exitosamente");

        } catch (SQLException ex) {
            Logger.getLogger(PanelIngresarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }

       //IMPRIMIMOS EL RECIBO DE INGRESO CON SU MATRICULA , NOMBRE Y HORA DE INGRESO
           String dest = "C:/reportes/sample.pdf";
        try {

            PdfWriter writer = new PdfWriter(dest);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document document = new Document(pdfDoc, PageSize.B7);
            this.getRootPane().setBackground(Color.yellow);// cambiamos el color del documento
            pdfDoc.addNewPage();

            Paragraph para = new Paragraph ("Recibo Parking\n Bienvenido a GestiónParking");


            para.setBorder(Border.NO_BORDER);
            para.setBold();

            Paragraph para1 = new Paragraph ("Matrícula vehículo: "+ tfMatricula.getText());
            Paragraph para2 = new Paragraph ("Nombre del propietario: "+tfPropietario.getText());
            Paragraph para3 = new Paragraph ("Hora de ingreso: "+fechaHora);
            Paragraph para4 = new Paragraph (".............No olvide registrarse para recibir descuentos");


            document.add(para);
            document.add(para1);
            document.add(para2);
            document.add(para3);
            document.add(para4);
            document.close();
             System.out.println("PDF Created");

        } catch (FileNotFoundException ex) {
            Logger.getLogger(PanelIngresarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

		if ((new File("c:\\reportes/sample.pdf")).exists()) {

			Process p = Runtime
			   .getRuntime()
			   .exec("rundll32 url.dll,FileProtocolHandler c:\\reportes/sample.pdf");
			p.waitFor();

		} else {

			System.out.println("File is not exists");

		}

		System.out.println("Done");

  	  } catch (Exception ex) {
		ex.printStackTrace();
	  }

            //FIN DE IMPRESION DE RECIBO DE INGRESO


    }//GEN-LAST:event_button1ActionPerformed

        private void tfPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPropietarioActionPerformed
                // TODO add your handling code here:


        }//GEN-LAST:event_tfPropietarioActionPerformed

        private void tfMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatriculaActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_tfMatriculaActionPerformed

        private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
                // TODO add your handling code here:
        }//GEN-LAST:event_formAncestorRemoved

        private void tfMatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMatriculaKeyReleased
               if(!tfMatricula.getText().isEmpty()){
		       button1.setEnabled(false);
	       }
	       else{
		       button1.setEnabled(false);
	       }
        }//GEN-LAST:event_tfMatriculaKeyReleased

        private void rbMotoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbMotoKeyReleased
              if(!rbMoto.getText().isEmpty()){
		      button1.setEnabled(false);

	      }else{
		      button1.setEnabled(false);
	      }
        }//GEN-LAST:event_rbMotoKeyReleased

        private void rbAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAutoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_rbAutoActionPerformed

        private void rbAutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbAutoKeyReleased
             if(!rbAuto.getText().isEmpty()){
		button1.setEnabled(false);
	}
	      else{
		      button1.setEnabled(false);
		      }
        }//GEN-LAST:event_rbAutoKeyReleased

        private void tfPropietarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPropietarioKeyReleased
               if(!tfPropietario.getText().isEmpty()){
		       button1.setEnabled(true);

	       }else{
		       button1.setEnabled(false);
	       }
        }//GEN-LAST:event_tfPropietarioKeyReleased


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private java.awt.Button button1;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JRadioButton rbAuto;
        private javax.swing.JRadioButton rbMoto;
        private javax.swing.JTextField tfMatricula;
        private javax.swing.JTextField tfPropietario;
        // End of variables declaration//GEN-END:variables

	
}
